---
 - hosts: planet-express

   tasks:
           - name: "finglet - install figlet"
             apt:
                     name: figlet
                     state: present
             become: True
